print("this is python code in github repo. v2")
print("this will be auto build in jenkins")
print("let's see either or not the build show without reloading the page")
print("let's see either or not the build show without reloading the page")
print("let's see jenkins can send email notification or not")